spring:
  r2dbc:
    username: root
    password: 123zxc
    url: r2dbcs:mysql://mysql:3306/testdb?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8

  redis:
    host: redis
    port: 6379
    password: 123zxc
    timeout: 5000

  data:
    redis:
      repositories:
        enabled: false

  rsocket:
    server:
      transport: websocket
      port: 8081

jwt:
  expiration:
    duration: 3600

my:
  filesPath:
    sqlScript: create_tables.sql
  mysql:
    host: mysql
    database: testdb