spring:
  r2dbc:
    username: root
    password: 123zxc
    url: r2dbcs:mysql://localhost:3306/mydb?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
  redis:
    host: localhost
    port: 6379
    password: 123zxc
    timeout: 5000

jwt:
  expiration:
    duration: 3600


